$schema: https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#
contentVersion: 1.0.0.0
parameters:
  appInsightsName:
    value: "[APPLICATION_INSIGHTS_NAME]"
  appInsightsKind:
    value: "[APPLICATION_INSIGHTS_KIND]"
